### PR TITLE
Add Release CI

### PR DESCRIPTION
**Pull request by idea404**
- Adds CI for auto-releasing tags
- Requires elevating rights for GH Actions for this repo before merging

### CODE REVIEW

**Comment by idea404** [comment]
worked here: https://github.com/idea404/zksolc-bin-test/actions/runs/6096088068/job/16540925427
Assumes new versions in all directories are all published at the same time / on the same commit to master/main branch

**Comment by hedgar2017** [comment]
@idea404 please request a review from the devops team - they are managing our GitHub Actions.

**Comment by andreyg-matterlabs** [comment]
Looks good to me

**Review by andreyg-matterlabs — APPROVED** [review]
Looks good

**Pull request merged**
